---
- name: install apache httpd
  hosts: [ node1.example.com, node2.example.com ]

  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: latest

  - name: Creating a file with content
    copy:
      dest: "/var/www/html/index.html"
      content: |
        Welcome to myweb server

  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started
      enabled: yes

  - firewalld:
      service: http
      permanent: yes
      state: enabled

  - name: check if splash is configured in the boot command
    lineinfile:
      backup: true
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX=".*net.ifnames=0 biosdevname=0'
      state: absent
    check_mode: true
    register: grub_cmdline_check
    changed_when: false

  - name: insert splash if missing
    lineinfile:
      backrefs: true
      path: /etc/default/grub
      regexp: "^(GRUB_CMDLINE_LINUX=\".*)\"$"
      line: '\1 net.ifnames=0 biosdevname=0"'
    when: grub_cmdline_check.found == 0
    notify: update grub
  
  - name: update grub
    shell: update-grub2