---
- name: install apache httpd
  hosts: [ node1.example.com, node2.example.com ]
  vars:
      anonymous_enable: yes
      local_enable: yes
      write_enable: yes
      anon_upload_enable: yes
      vsftp_root: /var/ftp/pub
      service_name: vsftpd

  tasks:
  - name: Install vsftpd and policycoreutils-python-utils
    yum:
      name: [ vsftpd, policycoreutils-python-utils ]
      state: latest

  - name: use template to copy FTP config
    template:
      src: vsftpd.j2
      dest: /etc/vsftpd/vsftpd.conf
    notify: restart service

  - name: Recursively change ownership of a directory
    file:
      path: "{{ vsftp_root }}"
      state: directory
      recurse: yes
      owner: ftp
      mode: '0755'
    notify: restart service

  - name: Start service vsftpd, if not started
    service:
      name: "{{ service_name }}"
      state: started
      enabled: yes

  - name: Allow full read/write access through SELinux
    seboolean:
      name: ftpd_full_access
      state: yes
      persistent: yes

  handlers:
  - name: restart service
    service:
      name: "{{ service_name }}"
      state: restarted

# ftpd_anon_write --> on
# ftpd_connect_all_unreserved --> off
# ftpd_connect_db --> off
# ftpd_full_access --> on
# ftpd_use_cifs --> off
# ftpd_use_fusefs --> off
# ftpd_use_nfs --> off
# ftpd_use_passive_mode --> off