---
- name: install apache httpd
  hosts: [ node1.example.com, node2.example.com ]
  vars:
      anonymous_enable: yes
      local_enable: yes
      write_enable: yes
      anon_upload_enable: yes
      vsftp_root: /var/ftp
      service_name: vsftpd
      service: ftp
      nopriv_user: ftp

  tasks:
  - name: Install vsftpd and policycoreutils-python-utils
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - "{{ service_name }}"
      - policycoreutils-python-utils

  - name: use template to copy FTP config
    template:
      src: vsftpd.j2
      dest: /etc/vsftpd/vsftpd.conf
    notify: restart service

  - name: Recursively change ownership of a directory
    file:
      path: "{{ vsftp_root }}"/pub
      state: directory
      recurse: yes
      owner: ftp
      mode: '0755'
    notify: restart service

  - name: Allow full read/write access through SELinux
    seboolean:
      name: ftpd_full_access
      state: yes
      persistent: yes

  - name: restart service
    service:
      name: "{{ service_name }}"
      state: restarted

  - name: Start service vsftpd, if not started
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - "{{ service_name }}"
      - firewalld
  
  - name: open network port
    firewalld:
      service: "{{ item }}"
      permanent: yes
      state: enabled
      immediate: yes
    with_items:
      - ftp
      
  handlers:
  - name: restart service
    service:
      name: "{{ service_name }}"
      state: restarted
  