---
- name: install apache httpd
  hosts: [ node1.example.com, node2.example.com ]
  vars:
      anonymous_enable: yes
      local_enable: yes
      write_enable: yes
      anon_upload_enable: yes
      vsftp_root: /var/ftp/pub

  tasks:
  - name: Install vsftpd
    yum:
      name: vsftpd
      state: latest

  - name: use template to copy FTP config
    template:
      src: vsftpd.j2
      dest: /etc/vsftpd/vsftpd.conf

  - name: Start service vsftpd, if not started
    service:
      name: vsftpd
      state: started
      enabled: yes

  - name: Check if ftpd_anon_write exists
    shell: getsebool -a | grep '^ftpd_anon_write\b'
    register: var_exists
    failed_when: false
    changed_when: false

  - name: Allow access to anon directories
    seboolean:
      name: ftpd_anon_write
      state: yes
      persistent: yes
    when: var_exists.rc == 0

  - name: Allow vsftpd to modify files in "{{ vsftp_root }}"
    sefcontext:
      target: "{{ vsftp_root }}(/.*)?"
      setype: ftpd_anon_write
      state: present
