---
- name: install apache httpd
  hosts: [ node1.example.com, node2.example.com ]
  vars:
      anonymous_enable: yes
      local_enable: yes
      write_enable: yes
      anon_upload_enable: yes
      vsftp_root: /var/ftp/pub
      service_name: vsftpd

  tasks:
  - name: Install vsftpd
    yum:
      name: vsftpd
      state: latest

  - name: use template to copy FTP config
    template:
      src: vsftpd.j2
      dest: /etc/vsftpd/vsftpd.conf
    notify: restart service

  - name: Recursively change ownership of a directory
    file:
      path: "{{ vsftp_root }}"
      state: directory
      recurse: yes
      owner: ftp
      mode: '0755'
    notify: restart service

  - name: Start service vsftpd, if not started
    service:
      name: "{{ service_name }}"
      state: started
      enabled: yes

  - name: Allow full read/write access through SELinux for el7+
    seboolean:
      name: ftpd_full_access
      state: yes
      persistent: yes

  - name: Check if ftp_home_dir exists
    shell: getsebool -a | grep '^ftp_home_dir\b'
    register: result
    failed_when: false
    changed_when: false
    tags: vsftpd

  - name: Allow access to home directories
    seboolean:
      name: ftp_home_dir
      state: yes
      persistent: yes
    when: result is succeeded
    tags: vsftpd

  handlers:
  - name: restart service
    service:
      name: "{{ service_name }}"
      state: restarted

