---
- name: Uninstall apache httpd
  hosts: [ node1.example.com, node2.example.com ]
  
  tasks:
  - name: Stop service httpd and disable it
    service:
      name: httpd
      state: stopped
      enabled: no
    ignore_errors: yes

  - name: Uninstall httpd
    yum:
      name: httpd
      state: absent

  - name: Remove file
    file:
      path: /var/www/html/index.html
      state: absent

  - firewalld:
      service: http
      permanent: yes
      state: disabled
      immediate: yes
