version: '3'
services:
  redis:
    image: redis
    volumes:
      - redis-data:/var/lib/redis/
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8080:80
volumes:
  redis-data:
    driver: local
